{% set name = "pixi-diff-to-markdown" %}
{% set version = "0.2.5" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pixi_diff_to_markdown-{{ version }}.tar.gz
  sha256: f221bc771124ab6cacf3161341bff7d59876a6aeab2c9bd57d97a0d7dcaf1514

build:
  entry_points:
    - pixi-diff-to-markdown = pixi_diff_to_markdown.__main__:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=2.10.2,<3
    - py-rattler >=0.8.2,<0.9
    - ordered_enum >=0.0.9,<0.0.10
    - typer >=0.15.0,<0.16
    - pydantic-settings >=2.6.1,<3
    - more-itertools >=10.5.0,<11

test:
  imports:
    - pixi_diff_to_markdown
  commands:
    - pip check
    - pixi-diff-to-markdown --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pavelzw/pixi-diff-to-markdown
  summary: Tool for converting `pixi update` diffs to markdown
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
