context:
  name: pixi-diff-to-markdown
  version: "0.3.5"
  python_min: '3.13'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: a7348c0b7ad43dd45bd01f3be6b8cc416fba9a04e524775b261bc205eabc892c

build:
  python:
    entry_points:
      - pixi-diff-to-markdown = pixi_diff_to_markdown.__main__:app
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >=2.11.7,<3
    - py-rattler >=0.15.0,<0.16
    - ordered-enum >=0.0.10,<0.0.11
    - typer >=0.16.0,<0.17
    - pydantic-settings >=2.10.1,<3
    - more-itertools >=10.7.0,<11

tests:
  - python:
      imports:
        - pixi_diff_to_markdown
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - pixi-diff-to-markdown --help

about:
  homepage: https://github.com/pavelzw/pixi-diff-to-markdown
  repository: https://github.com/pavelzw/pixi-diff-to-markdown
  documentation: https://pixi.sh/latest/advanced/updates_github_actions
  summary: Tool for converting `pixi update` diffs to markdown
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
