context:
  name: pixi-diff-to-markdown
  version: "0.3.2"
  python_min: '3.13'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 664a1935d4caf0a385e7da102093ccc54bbc37322735ce7b2d1fe911b686f7ef

build:
  python:
    entry_points:
      - pixi-diff-to-markdown = pixi_diff_to_markdown.__main__:app
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >=2.11.1,<3
    - py-rattler >=0.11.0,<0.12
    - ordered_enum >=0.0.9,<0.0.10
    - typer >=0.15.2,<0.16
    - pydantic-settings >=2.8.1,<3
    - more-itertools >=10.6.0,<11

tests:
  - python:
      imports:
        - pixi_diff_to_markdown
      pip_check: true
      python_version: ${{ python_min }}
  - script:
      - pixi-diff-to-markdown --help

about:
  homepage: https://github.com/pavelzw/pixi-diff-to-markdown
  repository: https://github.com/pavelzw/pixi-diff-to-markdown
  documentation: https://pixi.sh/latest/advanced/updates_github_actions
  summary: Tool for converting `pixi update` diffs to markdown
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
